//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlaplusWebApi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genotype
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public decimal Count { get; set; }
        public decimal Frequency { get; set; }
        public decimal LinkageDisequilibrium { get; set; }
        public string TypingMethod { get; set; }
        public string TypingReference { get; set; }
        public Nullable<System.DateTime> TypingDate { get; set; }
        public string TypingImgtVersion { get; set; }
        public string MiringReference { get; set; }
        public int CohortId { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public int CreatedByUserAccountId { get; set; }
        public Nullable<System.DateTimeOffset> LastModified { get; set; }
        public Nullable<int> LastModifiedByUserAccountId { get; set; }
    
        public virtual Cohort Cohort { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAccount UserAccount1 { get; set; }
    }
}
