//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlaplusWebApi.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hlaplusEntities : DbContext
    {
        public hlaplusEntities()
            : base("name=hlaplusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blacklist> Blacklists { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<Cohort> Cohorts { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Genotype> Genotypes { get; set; }
        public virtual DbSet<Haplotype> Haplotypes { get; set; }
        public virtual DbSet<HLAAntigenorAllele> HLAAntigenorAlleles { get; set; }
        public virtual DbSet<IdenticaNucleotideSequence> IdenticaNucleotideSequences { get; set; }
        public virtual DbSet<IdenticaPolypeptideSequence> IdenticaPolypeptideSequences { get; set; }
        public virtual DbSet<Internationalisation> Internationalisations { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Licence> Licences { get; set; }
        public virtual DbSet<Literal> Literals { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<NMDPMAC> NMDPMACs { get; set; }
        public virtual DbSet<nomenclature> nomenclatures { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<Population> Populations { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<Resolution> Resolutions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SerologicalEquivalent> SerologicalEquivalents { get; set; }
        public virtual DbSet<SerologicalRelationship> SerologicalRelationships { get; set; }
        public virtual DbSet<Timezone> Timezones { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
