//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlaplusWebApi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Population
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Population()
        {
            this.Cohorts = new HashSet<Cohort>();
            this.Haplotypes = new HashSet<Haplotype>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> DivLambda { get; set; }
        public Nullable<int> Div50 { get; set; }
        public Nullable<decimal> Div50Rel { get; set; }
        public Nullable<int> SampleSize { get; set; }
        public Nullable<int> SizeofPopulation { get; set; }
        public Nullable<decimal> PopulationGeneticsDiversity { get; set; }
        public Nullable<int> DivHeavyTail { get; set; }
        public Nullable<decimal> ResTrsCount { get; set; }
        public Nullable<decimal> ResTrs { get; set; }
        public Nullable<decimal> ResShareAmbig { get; set; }
        public Nullable<decimal> ResMissLoci { get; set; }
        public Nullable<decimal> DevHwe { get; set; }
        public Nullable<decimal> ErrStd { get; set; }
        public Nullable<decimal> ErrSamp80100 { get; set; }
        public Nullable<decimal> SumFreqGap { get; set; }
        public Nullable<decimal> ErrOffset { get; set; }
        public Nullable<decimal> LdMeasure { get; set; }
        public Nullable<decimal> KfoldImputable { get; set; }
        public Nullable<decimal> KfoldPredActual { get; set; }
        public Nullable<int> Kfoldn { get; set; }
        public string EmAlgorithm { get; set; }
        public string EmVersion { get; set; }
        public string EmAlgRef { get; set; }
        public string MacService { get; set; }
        public string MacSerRef { get; set; }
        public string MacVersion { get; set; }
        public string ArsService { get; set; }
        public string ArsServiceReference { get; set; }
        public string ArsVersion { get; set; }
        public string HweMethod { get; set; }
        public string HweReference { get; set; }
        public string LdMethod { get; set; }
        public string LdMethordReference { get; set; }
        public string EmParam { get; set; }
        public string ArsParam { get; set; }
        public string HweParam { get; set; }
        public int DistributionLicenceId { get; set; }
        public int OwnerOrganisationId { get; set; }
        public Nullable<int> ResolutionId { get; set; }
        public Nullable<int> HostedByOrgansiationId { get; set; }
        public Nullable<int> CalculatedByOrganisationId { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public int CreatedByUserAccountId { get; set; }
        public Nullable<System.DateTimeOffset> LastModified { get; set; }
        public Nullable<int> LastModifiedByUserAccountId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cohort> Cohorts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Haplotype> Haplotypes { get; set; }
        public virtual Licence Licence { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual Organisation Organisation1 { get; set; }
        public virtual Organisation Organisation2 { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAccount UserAccount1 { get; set; }
        public virtual Resolution Resolution { get; set; }
    }
}
