//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlaplusWebApi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Privilege()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool AuditLogViewOnly { get; set; }
        public bool SystemLogViewOnly { get; set; }
        public bool ScheduledServiceViewOnly { get; set; }
        public bool WebService { get; set; }
        public bool PopulationViewOnly { get; set; }
        public bool PopulationViewAndModify { get; set; }
        public bool CohortViewOnly { get; set; }
        public bool CohortViewAndModify { get; set; }
        public bool TimezoneViewOnly { get; set; }
        public bool TimezoneViewAndModify { get; set; }
        public bool BlacklistViewOnly { get; set; }
        public bool BlacklistViewAndModify { get; set; }
        public bool LiteralViewOnly { get; set; }
        public bool LiteralViewAndModify { get; set; }
        public bool GenotypeViewOnly { get; set; }
        public bool GenotypeViewAndModify { get; set; }
        public bool HaplotypeViewOnly { get; set; }
        public bool HaplotypeViewAndModify { get; set; }
        public bool HaplotypeImport { get; set; }
        public bool HaplotypeExport { get; set; }
        public bool LicenceViewOnly { get; set; }
        public bool LicenceViewAndModify { get; set; }
        public bool OrganisationViewOnly { get; set; }
        public bool OrganisationViewAndModify { get; set; }
        public bool RoleViewOnly { get; set; }
        public bool RoleViewAndModify { get; set; }
        public bool PrivilegeViewOnly { get; set; }
        public bool PrivilegeViewAndModify { get; set; }
        public bool UserAccountViewOnly { get; set; }
        public bool UserAccountViewAndModify { get; set; }
        public bool ChallengeViewOnly { get; set; }
        public bool ChallengeViewAndModify { get; set; }
        public bool ResolutionViewOnly { get; set; }
        public bool ResolutionViewAndModify { get; set; }
        public bool CountryViewOnly { get; set; }
        public bool CountryViewAndModify { get; set; }
        public bool LanguageViewOnly { get; set; }
        public bool LanguageViewAndModify { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public int CreatedByUserAccountId { get; set; }
        public Nullable<System.DateTimeOffset> LastModified { get; set; }
        public Nullable<int> LastModifiedByUserAccountId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAccount UserAccount1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
