//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HlaplusWebApi.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int OrganisationId { get; set; }
        public int PrivilegeId { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public System.DateTime EffectiveTo { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public int CreatedByUserAccountId { get; set; }
        public Nullable<System.DateTimeOffset> LastModified { get; set; }
        public Nullable<int> LastModifiedByUserAccountId { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual Privilege Privilege { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAccount UserAccount1 { get; set; }
        public virtual UserAccount UserAccount2 { get; set; }
    }
}
